#requires -Version 5.1
[CmdletBinding()]
param(
    [string]$EnvFile = ".env.compose.example",
    [string]$ProjectName = "user-admin",
    [string]$OutputFile = "compose.digests.yaml",
    [switch]$Pull
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (Get-Variable -Name PSNativeCommandUseErrorActionPreference -Scope Global -ErrorAction SilentlyContinue) {
    $PSNativeCommandUseErrorActionPreference = $true
}

$repoRoot = Split-Path -Parent $PSScriptRoot

function Resolve-RepoPath {
    param([string]$Path)

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return $Path
    }

    return (Join-Path $repoRoot $Path)
}

function Invoke-DockerComposeConfigJson {
    param([string]$EnvPath)

    $previousComposeEnvFile = $env:COMPOSE_ENV_FILE
    try {
        $env:COMPOSE_ENV_FILE = $EnvPath
        $output = & docker compose -p $ProjectName --env-file $EnvPath config --format json
        if ($LASTEXITCODE -ne 0) {
            throw "docker compose config --format json failed."
        }

        return (($output | ForEach-Object { $_.ToString() }) -join [Environment]::NewLine)
    } finally {
        $env:COMPOSE_ENV_FILE = $previousComposeEnvFile
    }
}

function Get-PinnedImageDigest {
    param([string]$Image)

    if ($Image -match "@sha256:[0-9a-fA-F]{64}$") {
        return $Image
    }

    if ($Pull) {
        docker pull $Image | Out-Host
        if ($LASTEXITCODE -ne 0) {
            throw "docker pull failed for $Image"
        }
    }

    $digest = docker image inspect --format "{{index .RepoDigests 0}}" $Image
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($digest)) {
        throw "No local RepoDigest found for $Image. Re-run with -Pull."
    }

    return $digest.Trim()
}

$envPath = Resolve-RepoPath $EnvFile
if (-not (Test-Path -LiteralPath $envPath)) {
    throw "Env file not found: $envPath"
}

$outputPath = Resolve-RepoPath $OutputFile
$configJson = Invoke-DockerComposeConfigJson -EnvPath $envPath
$config = $configJson | ConvertFrom-Json

$pinnedServices = @()
foreach ($service in $config.services.PSObject.Properties | Sort-Object Name) {
    $imageProperty = $service.Value.PSObject.Properties["image"]
    if (-not $imageProperty -or [string]::IsNullOrWhiteSpace([string]$imageProperty.Value)) {
        continue
    }

    $image = [string]$imageProperty.Value
    $pinnedServices += [pscustomobject]@{
        Service = $service.Name
        Image = Get-PinnedImageDigest -Image $image
    }
}

if ($pinnedServices.Count -eq 0) {
    throw "No image-based services were found in compose config."
}

$lines = @(
    "# Generated by ops/pin-compose-digests.ps1.",
    "# Use with: docker compose -f compose.yaml -f $OutputFile --env-file $EnvFile up -d",
    "services:"
)
foreach ($service in $pinnedServices) {
    $lines += "  $($service.Service):"
    $lines += "    image: `"$($service.Image)`""
}

Set-Content -LiteralPath $outputPath -Value $lines -Encoding UTF8

$pinnedServices | Format-Table -AutoSize
Write-Host "Digest override file written: $outputPath"
